config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # root 'users#current_user_show'
  devise_for :users, controllers: { registrations: 'registrations' }
  # post 'users/:id/subscribe_subject', :to => 'users#subscribe_subject'
  # post 'users/:id' => 'users#subscribe_subject', as: 'sub_subject'
  post '/users/:id' => 'users#subscribe_school', as: 'sub_school'
  delete '/users/:id' => 'users#unsubschool', as: 'unsub_school'
  get '/users/:id/schools' => 'users#schools', as: :users_schools
  resources :users do
    resources :schools
    resources :subjects_teachers
    resources :subjects
    resources :grades_subjects_teachers
  end
  resources :subjects_teachers do
    resources :users
  end
  resources :grades_subjects_teachers
  resources :reviews
  resources :schools do
    resources :users
    resources :subjects
  end

  resources :subjects do
    resources :subjects_teachers
    resources :users
  end
  resources :grades

  resources :planifications do
    resources :reviews
    resources :lectures
    get :add_lecture, on: :collection
  end

  get :send_code_email, to: 'schools#send_code_email', as: :send_code_email

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/grades_subjects_teacher.rb
class GradesSubjectsTeacher < ApplicationRecord
  validates :grade_id, uniqueness: { scope: :subjects_teacher_id }

  belongs_to :grade
  belongs_to :subjects_teacher
  has_many   :planifications
end

app/controllers/grades_subjects_teachers_controller.rb
class GradesSubjectsTeachersController < ApplicationController
  def show
    @grades_subjects_teacher = GradesSubjectsTeacher.find(params[:id])
    @grade = @grades_subjects_teacher.grade
    @user = @grades_subjects_teacher.subjects_teacher.user
    @subject = @grades_subjects_teacher.subjects_teacher.subject
  end

  def new
    @grades_subjects_teacher = GradesSubjectsTeacher.new
  end

  def edit; end

  def create
    @user = current_user
    @grades_subjects_teacher = GradesSubjectsTeacher.new(grades_subjects_teacher_params)
    respond_to do |format|
      if @grades_subjects_teacher.save
        format.html do
          redirect_to users_schools_path(@user), notice: 'Curso agregado con éxito.'
        end
        format.json do
          render :show, status: :created, location: @grades_subjects_teacher
        end
      else
        format.html do
          redirect_to users_schools_path(@user), notice: 'Curso inválido.'
        end
        format.json do
          render json: @grades_subjects_teacher.errors, status: :unprocessable_entity
        end
      end
    end
  end

  private

  def grades_subjects_teacher_params
    params.require(:grades_subjects_teacher).permit(:grade_id, :subjects_teacher_id)
  end
end

app/helpers/grades_subjects_teachers_helper.rb
module GradesSubjectsTeachersHelper
end

app/views/grades_subjects_teachers/_form.html.erb
<%= form_for @grades_subjects_teacher = GradesSubjectsTeacher.new do |form| %>

  <div class="field">
    <%= form.hidden_field :grade_id %>
    <%= form.select :grade_id, ["Agrega Nuevo Curso..."] | Grade.all.map { |g| [g.name, "#{g.id}"] }, {}, :class=>"select_box" %>
    <%= form.hidden_field :subjects_teacher_id %>
    <%= form.hidden_field :subjects_teacher_id, value: SubjectsTeacher.find_by(subject_id: subject.id, user_id: user.id).id %>

    <div class="add_button"><%= form.submit 'Agregar'%><div>
  </div>
<% end %>

app/views/grades_subjects_teachers/_modal_box.html.erb
<div class="modalJorge" id="plan-comment">
<div>
	<p class="comment">Incluir comentario:</p>
	<div class="input">
		<%= text_area_tag 'plan_comment' %>
	</div>
	<aside class="close">
		<button class="btn send-comment plan-state-change-utp">Enviar</button>
		<p>Cerrar <span class="X">[X]</span></p>
	</aside>
</div>
</div>

app/views/grades_subjects_teachers/_plan.html.erb
<tr>

  <td>
    <%= image_tag "140_document-icon.png", :size => "140x140" %>
  </td>
  <td>
    <p class="plan_header"><%= plan.name %></p>
    <p class="plan-state-show <%= plan.id %> plan_creator" >Estado:</p>
     <p class="plan_info"><%= plan.state ? "Edición por Profesor" : "Revisión por UTP" %></p>
    <p class="plan_creator">Creador Original: </p>
  <p class="plan_info"><%= plan.author_name %></p>
  <td>
    <%= link_to 'Ver', plan, :class => "planification-link plan-button", :method => :get  %><br>
    <% if current_user.role == 'Profesor' %>
      <%= link_to 'Editar', edit_planification_path(plan), :class => "planification-link plan-button", :method => :get   %><br>
      <%= link_to 'Eliminar', plan, method: :delete, data: { confirm: 'Are you sure?' }, :class=> "planification-link plan-button"%><br>
    <% end %>
  </td>

  <% if current_user.role == "Profesor" %>
    <td><button class="plan-state-change-prof <%= plan.id %> plan_id" data-planification-id="<%= plan.id %>" 
  <%= plan.state ? "enabled" : "disabled" %> >Notificar a UTP</button></td>




  <% elsif current_user.role == "Jefe UTP" %>
    <td><button class="modal-jorgeInput plan_id" data-planification-id="<%= plan.id %>" 
    <%= plan.state ? "disabled" : "enabled" %> >Notificar a Profesor</button></td>
    <aside>
      <% planId = plan.id %>
      <% planName = plan.name %>
      <%= render partial: 'planifications/modal_box', locals: { planId: planId, planName: planName } %>
    </aside>







  <% end %>

</tr>
<br>

app/views/grades_subjects_teachers/show.html.erb
	<h1> <%= @grade.name %> </h1>
	<h2 style="text-align: center"> <%= @subject.name %> </h2>
<div class="plan-box">
	<% @grades_subjects_teacher.planifications.each do |plan| %>
		<table class="plan_list_wrapper">
			<%= render partial: 'plan', locals: {plan: plan} %>
		</table>
	<% end %>

	<%= link_to 'Crear Planificación', new_planification_path(grades_subjects_teacher_id: @grades_subjects_teacher.id), class: "links button button-block", :method => :get  %>
</div>