config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # root 'users#current_user_show'
  devise_for :users, controllers: { registrations: 'registrations' }
  # post 'users/:id/subscribe_subject', :to => 'users#subscribe_subject'
  # post 'users/:id' => 'users#subscribe_subject', as: 'sub_subject'
  post '/users/:id' => 'users#subscribe_school', as: 'sub_school'
  delete '/users/:id' => 'users#unsubschool', as: 'unsub_school'
  get '/users/:id/schools' => 'users#schools', as: :users_schools
  resources :users do
    resources :schools
    resources :subjects_teachers
    resources :subjects
    resources :grades_subjects_teachers
  end
  resources :subjects_teachers do
    resources :users
  end
  resources :grades_subjects_teachers
  resources :reviews
  resources :schools do
    resources :users
    resources :subjects
  end

  resources :subjects do
    resources :subjects_teachers
    resources :users
  end
  resources :grades

  resources :planifications do
    resources :reviews
    resources :lectures
    get :add_lecture, on: :collection
  end

  get :send_code_email, to: 'schools#send_code_email', as: :send_code_email

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# User Model
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :avatar_file
  after_save :save_avatar, if: :avatar_file
  devise                  :database_authenticatable, :registerable,
                          :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :schools
  has_many :subjects_teachers
  has_many :subjects, through: :subjects_teachers
  has_many :grades_subjects_teachers, through: :subjects_teacher
  has_many :planifications, through: :grades_subjects_teachers
  has_many :reviews
  # accepts_nested_attributes_for :subjects_teachers,
  #                               allow_destroy: true,
  #                               reject_if: proc { |att| att['id'].blank? }
  # validates_associated :subjects_teachers

  def save_avatar
    filename = avatar_file.original_filename
    folder = "app/assets/images/users/#{id}/avatar"
    FileUtils.mkdir_p folder
    f = File.open File.join(folder, filename), 'wb'
    f.write avatar_file.read
    f.close

    self.avatar_file = nil
    update avatar: filename
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# UsersController
class UsersController < ApplicationController
  def index
    @users = User.all
    if request.xhr?
      render json: @users
    end
  end

  def show
    @user = User.find(params[:id])
    @subjects_teacher = @user.subjects_teachers.new
  end

  def current_user_show
    redirect_to current_user
  end
  def unsubschool
    @user = User.find(params[:id])
    schoolid = params[:schoolid]
    @school = School.find(schoolid)
    ss = []
    @user.subjects.each do |s|
      ss.append(s) if s.school_id == @school.id
    end
    @user.subjects.delete(ss)
    @user.schools.delete(@school)
    redirect_to users_schools_path, notice: 'Colegio eliminado.'
  end
  def subscribe_school
    @user = User.find(params[:id])
    schoolid = params[:schoolid]
    if schoolid == "Selecciona un colegio..."
      redirect_to users_schools_path, notice: 'Seleccione una opción válida.'
    elsif @user.schools.exists?(schoolid)
      redirect_to users_schools_path, notice: 'Usted ya está inscrito en este colegio.'
    elsif true # true = school secret code match
      @school = School.find(params[:schoolid])
      @user.schools << @school
      redirect_to users_schools_path, notice: 'Nuevo colegio agregado con éxito.'
    #else
      #@user.schools.delete(School.find(schoolid))
    end
  end

  def schools
    @user = User.find(params[:id])
    @subjects_teacher = @user.subjects_teachers.new
  end

  # def subscribe_subject
  #  @user = User.find(params[:id])
  #  subjectid = params[:subjectid]
  #  if @user.subjects.exists?(subjectid)
  #    redirect_to @user, notice: 'Usted ya agregó este curso en este colegio'
  #  else
  #    Subjects_User.create(subject_id: subjectid, user_id: @user.id)
  #  end
  # end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_teacher_schools.html.erb
<!DOCTYPE html>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<div class="info_form">

  <div class="w3-container">
    <% if @user.schools.any? %>
      <h3> Colegios en los que trabajas </h3>
    <% end %>
    <p id="notice"><%= notice %></p>
  <ul class="w3-ul">

    <% @user.schools.each do |school| %>
      <li>
        <div class="subject"><%= school.name %></div>
        <%= form_tag({controller: "users", action: "unsubschool"}, method: "delete") do |f| %>
          <%= hidden_field_tag "schoolid", school.id %>
          <div class="generate_button"><%= submit_tag("Eliminar") %></div>
        <% end %>
      </li>

      <div class="info_form">
      <ul>
        <h3>Asignaturas:</h3>
        <% @user.subjects.where(school_id: school.id).find_each do |subject| %>
          <li class="subject"><%= subject.name %></li>
          <ul>
            <div class="courses"> Cursos </div>
            <% @user.subjects_teachers.find_by(subject_id: subject.id).grades.each do |grade| %>
                <%= button_to grade.name, grades_subjects_teacher_path(GradesSubjectsTeacher.find_by(subjects_teacher_id: SubjectsTeacher.find_by(subject_id: subject.id, user_id: @user.id).id, grade_id: grade.id)),:class=>"links", :method => :get %>
            <% end %>

            <%= render partial: '/grades_subjects_teachers/form', locals: {user: @user, subject: subject} %>

          </ul>
        <% end %>
        <%= render partial: '/subjects_teachers/form', locals: {school: school} %>
      </ul>
    </div>
    <% end %>

    <div class="info_form">
    <h3> Agregar Nuevo Colegio </h3><br>
    <%= form_tag(:action => "subscribe_school") do |f| %>

      <div class="field">
      <%= select_tag "schoolid", options_for_select(["Selecciona un colegio..."] | School.all.map { |s| [s.name, "#{s.id}"] }) %>
      </div>
      <div class="courses">Ingresa el código del colegio</div>
      <%= text_field_tag "schoolCode", nil, placeholder: 'Código..' %>

      <br>
      <div class="add_button"><%= submit_tag "Agregar", id: "school-form-submit" %></div>
  <% end %>

  </ul>
  </div>

</div>
</html>

app/views/users/_utp_schools.html.erb
<p id="notice"><%= notice %></p>
<div class="info_form">
  <h3> Escuelas Registradas </h3>
  <% @user.schools.each do |school| %>

    <p> <%= button_to school.name, school_path(school.id), :class=>"links", :method => :get %> </p>
    <% if can? :destroy, school %>
    	<%= link_to 'Eliminar', school, method: :delete, data: { confirm: '¿Estás seguro(a) que deseas eliminar esta escuela?' } %></td>
    <% end %>

  <% end %>


  <% if can? :create, School %>
    <%= button_to "Ingresar Nuevo Colegio", new_school_path, :class=>"links", :method => :get %>
  <% end %>
</div>

app/views/users/schools.html.erb
<% if @user.role == "Profesor" %>
    <%= render 'teacher_schools', user: @user %>
  <% elsif @user.role == "Jefe UTP" %>
    <%= render 'utp_schools', user: @user %>
  <% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="form">
  <div class="info_label">
    <strong>Nombre:</strong>
    <h5><%= @user.name %> <%= @user.lastname %></h5>
  </div>

  <div class="info_label">
    <strong>Fecha de Nacimiento:</strong>
    <h5><%= @user.dob %></h5>
  </div>

  <div class="info_label">
    <strong>Teléfono de Contacto:</strong>
    <h5><%= @user.phone %></h5>
  </div>

  <div class="info_label">
    <strong>Dirección de Correo Electrónico:</strong>
    <h5><%= @user.email %></h5>
  </div>

  <div class="info_label">
    <strong>Rol:</strong>
    <h5><%= @user.role %></h5>
  </div>

  <%= button_to 'Editar información de usuario', edit_registration_path(@user), :class=>"links", :method => :get %>
</div>