config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # root 'users#current_user_show'
  devise_for :users, controllers: { registrations: 'registrations' }
  # post 'users/:id/subscribe_subject', :to => 'users#subscribe_subject'
  # post 'users/:id' => 'users#subscribe_subject', as: 'sub_subject'
  post '/users/:id' => 'users#subscribe_school', as: 'sub_school'
  delete '/users/:id' => 'users#unsubschool', as: 'unsub_school'
  get '/users/:id/schools' => 'users#schools', as: :users_schools
  resources :users do
    resources :schools
    resources :subjects_teachers
    resources :subjects
    resources :grades_subjects_teachers
  end
  resources :subjects_teachers do
    resources :users
  end
  resources :grades_subjects_teachers
  resources :reviews
  resources :schools do
    resources :users
    resources :subjects
  end

  resources :subjects do
    resources :subjects_teachers
    resources :users
  end
  resources :grades

  resources :planifications do
    resources :reviews
    resources :lectures
    get :add_lecture, on: :collection
  end

  get :send_code_email, to: 'schools#send_code_email', as: :send_code_email

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/school.rb
# School Model
class School < ApplicationRecord
  has_and_belongs_to_many :users
  has_many                :subjects, dependent: :destroy
  has_many                :grades

  validates :name, uniqueness: true
  validates :RBD,  uniqueness: true
  # No es necesario ingresar codigo para creacion de colegio
  validates :code, presence: false
end

app/controllers/schools_controller.rb
# SchoolsController
class SchoolsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show

    # Para que el prof. no pueda ver el código del colegio ingresando
    # a la URL del colegio en formato JSON, sólo TODOS los datos del
    # colegio son accesibles con request AJAX.
    respond_to do |format|
      if request.xhr?
        format.html { render :show }
        format.json { render json: @school }
      else
        authorize! :read, School
        format.html { render :show }
        format.json { render nothing: true }
      end
    end
  end

  # GET /schools/new
  def new
    authorize! :create, School
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
    authorize! :update, @school
  end

  # POST /schools
  # POST /schools.json
  def create
    authorize! :create, School
    @user = current_user
    @school = @user.schools.build(school_params)
    @school.user_id = @user.id
    @user.schools << @school
    respond_to do |format|
      if @school.save
        format.html do
          redirect_to users_schools_path(@user), notice: 'Colegio creado con éxito.'
        end
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json do
          render json: @school.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    authorize! :update, @school

    respond_to do |format|
      if @school.update(school_params)
        format.html do
          redirect_to @school, notice: 'Colegio editado con éxito'
        end
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json do
          render json: @school.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    authorize! :destroy, @school
    @school.destroy
    respond_to do |format|
      format.html do
        redirect_to schools_url, notice: 'Escuela eliminada con éxito.'
      end
      format.json { head :no_content }
    end
  end

  def send_code_email
    # En la Web Console del browser tirará un "no element found"..
    # esto porque no sabe qué renderizar al llegar a esta ruta,
    # pero el email se envía igual.
    @prof = User.find_by_id(params[:prof_id])
    @school = School.find_by_id(params[:school_id])
    CodeMailer.school_code_email(@prof, @school).deliver_later
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_school
    @school = School.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def school_params
    params.require(:school).permit(:name, :RBD, :address, :phone, :code)
  end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_with(model: school, local: true) do |form| %>
  <% if school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form">
  <div class="field">
    <%= form.label :nombre %></br>
    <%= form.text_field :name, id: :school_name %>
  </div>

  <div class="field">
    <%= form.label :RBD %></br>
    <%= form.text_field :RBD, id: :school_RBD %>
  </div>

  <div class="field">
    <%= form.label :dirección %></br>
    <%= form.text_field :address, id: :school_address %>
  </div>

  <div class="field">
    <%= form.label :teléfono %></br>
    <%= form.text_field :phone, id: :school_phone %>
  </div>

  <div class="info_form">
    <div style="cursor:pointer;" class="generate_button button-block" id="new-school-code-generator">
      Generar Código
    </div></br>
    <div class="info_label">Código: <p style="display:inline;" class="code-paragraph"></p>
    </div>
  </div>

  <%= form.hidden_field :code, id: :school_code, class: "code-paragraph", value: "" %>

  <div class="actions">
    <div class="button button-block">
      <%= form.submit "Crear Escuela" %>
    </div>
  </div>


</div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing School</h1>

<%= render 'form', school: @school %>

<%= button_to 'Ver', @school, :class=>"links", :method => :get %> |
<%= button_to 'Atrás', schools_path, :class=>"links", :method => :get %>

app/views/schools/index.html.erb
<p id="notice"><%= notice %></p>

<% if @user.role == "Profesor" %>
  <%= render 'teacher_schools', user: @user %>
<% elsif @user.role == "Jefe UTP" %>
  <%= render 'utp_schools', user: @user %>
<% else %>
  <h1>Schools</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Rbd</th>
        <th>Address</th>
        <th>Phone</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @schools.each do |school| %>
        <tr>
          <td><%= school.name %></td>
          <td><%= school.RBD %></td>
          <td><%= school.address %></td>
          <td><%= school.phone %></td>
          <td><%= link_to 'Show', school %></td>
          <% if can? :update, school %>
            <td><%= link_to 'Edit', edit_school_path(school) %></td>
          <% end %>
          <% if can? :destroy, school %>
            <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= button_to 'New School', new_school_path, :class=>"links", :method => :get %>
<% end %>

app/views/schools/new.html.erb
<h1>Nueva Escuela</h1>

<%= render 'form', school: @school %>

<%= button_to 'Atrás', user_path(current_user.id), :class=>"links", :method => :get %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>
<div class="info_form">
  <div class="info_label">
    <strong>Name:</strong>
    <%= @school.name %>
  </div>
  <div class="info_label">
    <strong>Rbd:</strong>
    <%= @school.RBD %>
  </div>
  <div class="info_label">
    <strong>Address:</strong>
    <%= @school.address %>
  </div>
  <div class="info_label">
    <strong>Phone:</strong>
    <%= @school.phone %>
  </div>
</div>

<%= button_to 'Editar información del colegio', edit_school_path(@school), :class=>"links", :method => :get %></br>

<div class="info_form">
<% if @school.subjects.any? %>

  <h3> Asignaturas dictadas en Colegio <%= @school.name %>: </h3>
  <div class="info_label">
  <% @school.subjects.each do |s| %>
    <strong><%= s.name %></strong>



<!-- CHANTARLE  -->
    <%= link_to "Ver planificaciones", school_subject_path(school_id: s.school_id, id: s.id) %>
                 



      <% if(current_user.role == 'Jefe UTP') %>
        <%= button_to 'Eliminar', school_subject_path(s.school, s) ,:class=>"links", :method => :delete %> </p>
      <% end %>
      <br>
  <% end %>
  </div>
  <% end %>

  <div class="info_form">
  <h3> Agregar nueva asignatura </h3>
    <%= form_for([@school, @school.subjects.build]) do |f| %>
      <div class = "field">
        <%= f.label :name, 'Nombre de la Asignatura' %></br>
        <%= f.text_field :name %>
      </div>
      <div class = "field">
        <%= f.label :description, 'Descripción de la Asignatura (opcional)' %></br>
        <div class="text_area"><%= f.text_area :description %></div>
      </div>
      <div class="actions">
        <div class="button button-block">
          <%= f.submit "Crear Asignatura" %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<br>

<div class="info_form code">
  <div style="cursor:pointer;" class="generate_button button-block" id="show-school-code-generator">
    Generar Código
  </div></br>
  <div class="info_label" id="school-id" data-school-id="<%= @school.id %>">Código: <p style="display:inline;" class="code-paragraph"><%= @school.code %></p>
  </div>
</div>

<div class="info_form">
  <div class="code-mailer info_label">Enviar código a profesor: 
    <input placeholder="profesor" class="prof-mail username"></input>@<input placeholder="dominio.com" class="prof-mail domain"></input>
  </div>

  <button id="send-email-code" style="color:white;">Enviar</button> 

</div>
<%= button_to 'Atrás', users_schools_path(current_user.id), :class=>"links", :method => :get %>