config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # root 'users#current_user_show'
  devise_for :users, controllers: { registrations: 'registrations' }
  # post 'users/:id/subscribe_subject', :to => 'users#subscribe_subject'
  # post 'users/:id' => 'users#subscribe_subject', as: 'sub_subject'
  post '/users/:id' => 'users#subscribe_school', as: 'sub_school'
  delete '/users/:id' => 'users#unsubschool', as: 'unsub_school'
  get '/users/:id/schools' => 'users#schools', as: :users_schools
  resources :users do
    resources :schools
    resources :subjects_teachers
    resources :subjects
    resources :grades_subjects_teachers
  end
  resources :subjects_teachers do
    resources :users
  end
  resources :grades_subjects_teachers
  resources :reviews
  resources :schools do
    resources :users
    resources :subjects
  end

  resources :subjects do
    resources :subjects_teachers
    resources :users
  end
  resources :grades

  resources :planifications do
    resources :reviews
    resources :lectures
    get :add_lecture, on: :collection
  end

  get :send_code_email, to: 'schools#send_code_email', as: :send_code_email

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Planef</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if user_signed_in? %>
      <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <div>
          <div class="round-image-70">
            <% if current_user.avatar? %>
              <%= image_tag "users/#{current_user.id}/avatar/#{current_user.avatar}", :size => "140x140" %>
            <% else %>
              <%= image_tag "default_teacher_avatar.png", :size => "140x140" %>
            <% end %>
          </div>
          <p class="sidenav_header"> Hola <br><br><%= current_user.name %>! </p>
          <p> <%= link_to "Mi Perfil", user_path(current_user.id) %> </p>
          <p> <%= link_to "Colegios", users_schools_path(current_user) %> </p>
          <p> <%= link_to "Buscador de<br><br>Planifaciones".html_safe, planifications_path %></p>
          <p> <%= link_to "Cerrar Sesion", destroy_user_session_path, :method => 'delete' %></p>
        </div>
      </div>
    <% end %>

  <!-- Add all page content inside this div if you want the side nav to push page content to the right (not used if you only want the sidenav to sit on top of the page -->
    <div id="main">
      <%= yield %>
    </div>
  </body>
</html>